#The number of ticks that a spear, kunai or tensura arrow needs to be on ground to despawn.
spearDespawnTick = 600
#The number of ticks that a thrown item (normally by Thrower) needs to be on ground to despawn.
thrownItemDespawnTick = 400
#The number of ticks that a magic entity needs to despawn by default if not custom set.
magicDespawnTick = 400
#How many blocks away from the shooter that a magic projectile needs to be to despawn.
#Set to a value higher than 0 to enable this.
magicDespawnRange = -1.0
#The number of ticks that a magic projectile needs to despawn by default if not custom set.
projectileDespawnTick = 100
#How many blocks away from the shooter that a magic projectile needs to be to despawn.
#Set to a value higher than 0 to enable this.
projectileDespawnRange = -1.0
