#Base magicule value for a chunk.
baseMagicule = 500.0
#Base magicule regeneration per second for a chunk.
baseMagiculeRegeneration = 10.0
#How often maxMagiculeModifier are updated in ticks.
modifierUpdateInterval = 200
#Seed for magicule generation", "Changing this will change the magicule values for all chunks.
magiculeSeed = -8850729660021211509
#The amount that a magic engine will reduce from surrounding chunks (replace the blocks to apply the new value).
magicEngineReduction = 1000.0
#The radius in block that a magic engine will affect on entities (replace the blocks to apply the new value).
magicEngineRange = 16.0
#The amount that a labyrinth magic engine will reduce from surrounding chunks (replace the blocks to apply the new value).
labyrinthMagicEngineReduction = 10000.0
#The radius in block that a labyrinth magic engine will affect on entities (replace the blocks to apply the new value).
labyrinthMagicEngineRange = 32.0
#The minimal amount of Magicule in a chunk to allow mob spawn.
minimalMagiculeSpawn = 10.0
#The maximum amount of magicule value a chunk can get.
maximumMagicule = 1000000.0
