#One of how many chances for an otherworlder to spawn as Luminous.
luminousChance = 0
#One of how many chances for an otherworlder to spawn as Rimuru.
rimuruChance = 0
#One of how many chances for an otherworlder to spawn as Carrion.
carrionChance = 0
