[BulletPunch]
	#The cooldown in seconds.
	cooldown = 15
	#The cooldown in seconds when the skill is mastered.
	cooldownMastered = 15
	#The amount of punches.
	amount = 4

[ClangorousSoul]
	#The radius of the taunt.
	tauntRadius = 10
	#The radius of the taunt when the skill is mastered.
	tauntRadiusMastered = 15
	#The cooldown in seconds.
	cooldown = 60
	#The cooldown in seconds when the skill is mastered.
	cooldownMastered = 45

[Discharge]
	#Magicule Cost to activate.
	magiculeCost = 1000.0
	#How much damage that the Lightning Bolt does when activated.
	boltDamage = 15
	#The range for damage that the Lightning Bolt does when activated.
	boltRange = 3
	#The selection range of the target in blocks.
	selectionRange = 30
	#The cooldown in seconds.
	cooldown = 5

[Dissonance]
	#Magicule Cost to activate.
	magiculeCost = 10000.0
	#How much damage that the Lightning Bolt does when activated.
	boltDamage = 30
	#The range for damage that the Lightning Bolt does when activated.
	boltRange = 5
	#The selection range of the target in blocks.
	selectionRange = 30
	#The cooldown in seconds.
	cooldown = 5
	#The radius of effect.
	radius = 5

[Exoskeleton]
	#The amount of EP needed for Hihi'irokane Armor's stats.
	hihiirokaneEP = 4000000.0
	#The amount of EP needed for Monster Leather Special A Armor's stats.
	mlSAEP = 800000.0
	#The amount of EP needed for Monster Leather A Armor's stats.
	mlAEP = 80000.0
	#The amount of EP needed for Monster Leather B Armor's stats.
	mlBEP = 50000.0

[HellGate]
	#The cooldown in seconds.
	cooldown = 600
	#The cooldown in seconds when the skill is mastered.
	cooldownMastered = 300

[HellHall]
	#Magicule Cost to activate.
	magiculeCost = 5000.0
	#The cooldown in seconds.
	cooldown = 600
	#The cooldown in seconds when the skill is mastered.
	cooldownMastered = 600
	#The radius.
	radius = 4
	#The radius when the skill is mastered.
	radiusMastered = 4

[LethalPoison]
	#The duration of the poison effect in ticks. (Multiply seconds by 20.)
	duration = 200
	#The level of the poison effect.
	level = 3
	#The level of the poison effect when the skill is mastered.
	levelMastered = 6

[LightningMode]
	#Magicule Cost to activate.
	magiculeCost = 0.0
	#The duration in tick of the Transformation.
	transformationDuration = 3600
	#The duration in tick of the Transformation.
	transformationDurationMastered = 7200
	#The Cooldown in second after activation.
	cooldown = 1200

[MagisteelBody]
	#The amount of EP needed for Hihi'irokane Armor's stats.
	hihiirokaneEP = 1000000.0
	#The amount of EP needed for Adamantite's stats.
	adamantiteEP = 500000.0
	#The amount of EP needed for Pure Magisteel's stats.
	pureMagisteelEP = 100000.0
	#The amount of EP needed for High Magisteel's stats.
	highMagisteelEP = 50000.0

[Relapse]
	#The level of Fragility given to a clone created by the Aleph mode, when the user is a Forgotten.
	alephCloneFragilityForgotten = 2
	#The level of Slowness given to a clone created by the Aleph mode, when the user is a Forgotten.
	alephCloneSlownessForgotten = 5
	#The level of Fragility given to a clone created by the Aleph mode, when the user is a Remnant.
	alephCloneFragilityRemnant = 2
	#The level of Slowness given to a clone created by the Aleph mode, when the user is a Remnant.
	alephCloneSlownessRemnant = 4
	#The level of Fragility given to a clone created by the Aleph mode, when the user is an Empty or Whole.
	alephCloneFragilityEmptyWhole = 1
	#The level of Slowness given to a clone created by the Aleph mode, when the user is an Empty or Whole.
	alephCloneSlownessEmptyWhole = 3
	#The level of Fragility given to a clone created by the Aleph mode, when the user is a Revenant or Ascended.
	alephCloneFragilityRevenantAscended = 1
	#The level of Slowness given to a clone created by the Aleph mode, when the user is a Revenant or Ascended.
	alephCloneSlownessRevenantAscended = 1
	#The level of Fragility given to a clone created by the Aleph mode, when the user is a Divine Inferius or Divine Excelsius.
	alephCloneFragilityInferiusExcelsius = 0
	#The level of Slowness given to a clone created by the Aleph mode, when the user is a Divine Inferius or Divine Excelsius.
	alephCloneSlownessInferiusExcelsius = 0
	#The cooldown of the Aleph mode, when the user is a Forgotten in seconds.
	alephCooldownForgotten = 300
	#The cooldown of the Aleph mode, when the user is a Remnant in seconds.
	alephCooldownRemnant = 240
	#The cooldown of the Aleph mode, when the user is an Empty or Whole in seconds.
	alephCooldownEmptyWhole = 180
	#The cooldown of the Aleph mode, when the user is a Revenant or Ascended in seconds.
	alephCooldownRevenantAscended = 120
	#The cooldown of the Aleph mode, when the user is a Divine Inferius or Divine Excelsius in seconds.
	alephCooldownInferiusExcelsius = 60
	#The amount of clones summoned with the Bet mode, when the user is a Remnant.
	betClonesSummonedRemnant = 5
	#The amount of clones summoned with the Bet mode, when the user is an Empty or Whole.
	betClonesSummonedEmptyWhole = 7
	#The amount of clones summoned with the Bet mode, when the user is a Revenant or Ascended.
	betClonesSummonedRevenantAscended = 10
	#The amount of clones summoned with the Bet mode, when the user is a Divine Inferius or Divine Excelsius.
	betClonesSummonedInferiusExcelsius = 10
	#The cooldown of the Bet mode, when the user is a Remnant in seconds.
	betCooldownRemnant = 300
	#The cooldown of the Bet mode, when the user is an Empty or Whole in seconds.
	betCooldownEmptyWhole = 180
	#The cooldown of the Bet mode, when the user is a Revenant or Ascended in seconds.
	betCooldownRevenantAscended = 120
	#The cooldown of the Bet mode, when the user is a Divine Inferius or Divine Excelsius in seconds.
	betCooldownInferiusExcelsius = 60
	#The number of kills required for the user to use Gimel if the user is an Empty.
	gimelEmptyKills = 10
	#The number of kills required for the user to use Gimel if the user is a Revenant.
	gimelRevenantKills = 50
	#The number of kills required for the user to use Gimel if the user has achieved Divinity.
	gimelInferiusKills = 100
	#The cooldown of the Gimel mode if the user is an Empty.
	gimelCooldownEmpty = 180
	#The cooldown of the Gimel mode if the user is a Revenant.
	gimelCooldownRevenant = 120
	#The cooldown of the Gimel mode if the user is a Divine Inferius.
	gimelCooldownInferius = 60
	#The number of beams that descend onto a target if the user is a Whole.
	gimelBeamsWhole = 3
	#The damage of the beams that descend onto a target if the user is a Whole.
	gimelDamageWhole = 30.0
	#The number of beams that descend onto a target if the user is an Ascended.
	gimelBeamsAscended = 5
	#The damage of the beams that descend onto a target if the user is an Ascended.
	gimelDamageAscended = 40.0
	#The number of beams that descend onto a target if the user is a Divine Excelsius.
	gimelBeamsExcelsius = 10
	#The damage of the beams that descend onto a target if the user is a Divine Excelsius.
	gimelDamageExcelsius = 50.0
	#The duration in seconds that target marking will last while Gimel is activated on the Excelsius path.
	gimelDurationHoly = 30
	#The cooldown of the Gimel mode if the user is a Whole.
	gimelCooldownWhole = 180
	#The cooldown of the Gimel mode if the user is an Ascended.
	gimelCooldownAscended = 120
	#The cooldown of the Gimel mode if the user is a Divine Excelsius.
	gimelCooldownExcelsius = 60
	#The duration of the Daleth mode if the user is a Revenant, in seconds.
	dalethDurationRevenant = 30
	#The cooldown of the Daleth mode if the user is a Divine Inferius, in seconds.
	dalethDurationInferius = 60
	#The duration of the Daleth mode if the user is an Ascended, in seconds.
	dalethDurationAscended = 30
	#The cooldown of the Daleth mode if the user is a Divine Excelsius, in seconds.
	dalethDurationExcelsius = 60
	#The cooldown of the Daleth mode if the user is a Revenant, in seconds.
	dalethCooldownRevenant = 600
	#The cooldown of the Daleth mode if the user is a Divine Inferius, in seconds.
	dalethCooldownInferius = 300
	#The cooldown of the Daleth mode if the user is an Ascended, in seconds.
	dalethCooldownAscended = 600
	#The cooldown of the Daleth mode if the user is a Divine Excelsius, in seconds.
	dalethCooldownExcelsius = 300
	#The cooldown placed on both Aleph and Aleph: Null when Aleph: Null is used as a Divine Inferius.
	alephNullCooldownInferius = 600
	#The seconds of Collective given to the user if the user uses Aleph: Null as a Divine Inferius.
	alephNullInferiusCollective = 120
	#The cooldown placed on both Aleph and Aleph: Null when Aleph: Null is used as a Divine Excelsius.
	alephNullCooldownExcelsius = 300
	#The range of the Aleph: Null mode, when the user is a Divine Excelsius.
	alephNullExcelsiusRange = 20
	#The seconds of invincibility given to an Aleph clone if the user uses Aleph: Null as a Divine Excelsius.
	alephNullExcelsiusInvincibility = 60

[Spark]
	#The duration of the burn effect in ticks. (Multiply seconds by 20.)
	burnDuration = 100
	#The duration of the burn effect when mastered, in ticks. (Multiply seconds by 20.)
	burnDurationMastered = 200
	#The cooldown in seconds.
	cooldown = 15
	#The cooldown when mastered, in seconds.
	cooldownMastered = 15

[Tenacity]
	#Aura Cost per HP regenerated.
	auraCost = 100.0
	#Aura Cost per HP regenerated when mastered.
	auraCostMastered = 60.0
	#Should Tenacity heal the spiritual body when the skill is mastered?
	shouldRegenSHPOnMastery = true
	#Aura Cost per SHP regenerated.
	shpAuraCost = 120.0
	#Aura Cost per SHP regenerated when mastered.
	shpAuraCostMastered = 80.0
