[BrimstoneFlames]
	#How much damage that the effect Brimstone Flames does each second per level.
	brimstoneFlamesDamage = 15.0
	#Should Brimstone Flames bypass Resistances and degrade Nullifications?
	brimstoneFlamesBypassResistances = true
	#Should Brimstone Flames cancel Ultraspeed Regeneration?
	brimstoneFlamesBypassUSR = true
	#Should Brimstone Flames cancel Infinite Regeneration?
	brimstoneFlamesBypassIR = true
