[modName]
	# Nome: Formato do nome do mod
	# Descrição: Formatação para os nomes dos mods nas dicas de ferramenta para interfaces do JEI. Deixe em branco para desabilitar.
	# Valores válidos: A chat formatting string.
	# Use these formatting colors:
	# black dark_blue dark_green dark_aqua dark_red dark_purple gold gray dark_gray blue green aqua red light_purple yellow white
	# With these formatting options:
	# obfuscated bold strikethrough underline italic
	# Valor padrão: blue italic
	modNameFormat = blue italic


