[appearance]
	# Nome: Centralizar barra de pesquisa
	# Descrição: Move a barra de pesquisa do JEI para o centro inferior da tela.
	# Valores válidos: [true, false]
	# Valor padrão: false
	centerSearch = false

	# Nome: Altura da interface de receitas
	# Descrição: A altura máxima para a interface de receitas (em pixels).
	# Valores válidos: Any integer greater than or equal to 175
	# Valor padrão: 350
	recipeGuiHeight = 350


[cheating]
	# Nome: Modo de dar
	# Descrição: Escolha se o JEI deve dar ingredientes diretamente no inventário ou pegá-los com o mouse.
	# Valores válidos: [INVENTORY, MOUSE_PICKUP]
	# Valor padrão: MOUSE_PICKUP
	giveMode = MOUSE_PICKUP

	# Nome: Trapacear itens para barra de atalhos usando teclas
	# Descrição: Habilita trapacear itens para a barra de atalhos usando shift + teclas numéricas.
	# Valores válidos: [true, false]
	# Valor padrão: false
	cheatToHotbarUsingHotkeysEnabled = false

	# Nome: Mostrar ingredientes ocultos
	# Descrição: Habilita mostrar ingredientes que não estão no menu criativo.
	# Valores válidos: [true, false]
	# Valor padrão: false
	showHiddenIngredients = false

	# Nome: Mostrar receitas de tags
	# Descrição: Mostra receitas para tags de ingredientes como tags de itens e tags de blocos.
	# Valores válidos: [true, false]
	# Valor padrão: false
	showTagRecipesEnabled = false


[bookmarks]
	# Nome: Adicionar favoritos ao início
	# Descrição: Quando verdadeiro, adiciona novos favoritos ao início da lista. Quando falso, adiciona-os ao final.
	# Valores válidos: [true, false]
	# Valor padrão: false
	addBookmarksToFrontEnabled = false

	# Nome: Arrastar para reorganizar favoritos
	# Descrição: Habilita arrastar favoritos para reorganizá-los na lista.
	# Valores válidos: [true, false]
	# Valor padrão: true
	dragToRearrangeBookmarksEnabled = true


[tooltips]
	# Nome: Recursos de dicas de favoritos
	# Descrição: Recursos extras para dicas de ferramenta de favoritos.
	# Valores válidos: A comma-separated list containing values of:
	# [PREVIEW, INGREDIENTS]
	# Valor padrão: PREVIEW
	bookmarkTooltipFeatures = PREVIEW

	# Nome: Shift para dicas de favoritos
	# Descrição: Segure shift para mostrar recursos da dica de ferramenta de favoritos.
	# Valores válidos: [true, false]
	# Valor padrão: true
	holdShiftToShowBookmarkTooltipFeatures = true

	# Nome: Mostrar nomes de abas do criativo
	# Descrição: Mostra nomes das abas do criativo nas dicas de ferramenta dos ingredientes.
	# Valores válidos: [true, false]
	# Valor padrão: false
	showCreativeTabNamesEnabled = false

	# Nome: Mostrar conteúdo da tag
	# Descrição: Mostra o conteúdo da tag nas dicas de ferramenta ao navegar pelos ingredientes da receita.
	# Valores válidos: [true, false]
	# Valor padrão: true
	tagContentTooltipEnabled = true

	# Nome: Ocultar conteúdo de tag de ingrediente único
	# Descrição: Oculta o conteúdo da tag nas dicas de ferramenta quando há apenas um ingrediente na tag.
	# Valores válidos: [true, false]
	# Valor padrão: true
	hideSingleTagContentTooltipEnabled = true

	# Nome: Resumo de ingredientes da receita
	# Descrição: Mostra um resumo dos ingredientes necessários para uma receita, na dica de ferramenta do seu ingrediente de saída.
	# Valores válidos: [true, false]
	# Valor padrão: false
	enableRecipesGuiIngredientsSummary = false


[performance]
	# Nome: Pesquisa de baixa memória
	# Descrição: Define a pesquisa para o modo de baixa memória (torna a pesquisa lenta, mas usa menos RAM).
	# Valores válidos: [true, false]
	# Valor padrão: false
	lowMemorySlowSearchEnabled = false


[lookups]
	# Nome: Consultar conteúdos de fluidos
	# Descrição: Ao consultar receitas com itens que contêm fluidos, consultar também receitas para os fluidos.
	# Valores válidos: [true, false]
	# Valor padrão: false
	lookupFluidContentsEnabled = false

	# Nome: Consultar tags de bloco de item
	# Descrição: Ao pesquisar por tags de itens, incluir também tags para os blocos padrão contidos nos itens.
	# Valores válidos: [true, false]
	# Valor padrão: true
	lookupBlockTagsEnabled = true


[lookupHistory]
	# Nome: Habilitado
	# Descrição: Exibe ou oculta a sobreposição do histórico de pesquisa.
	# Valores válidos: [true, false]
	# Valor padrão: false
	enabled = false

	# Nome: Máximo de linhas
	# Descrição: Número máximo de linhas para exibir na sobreposição do histórico de pesquisa.
	# Valores válidos: An integer in the range [1, 7] (inclusive)
	# Valor padrão: 2
	maxRows = 2

	# Nome: Máximo de ingredientes
	# Descrição: Número máximo de ingredientes do histórico de pesquisa para salvar.
	# Valores válidos: An integer in the range [10, 1000] (inclusive)
	# Valor padrão: 100
	maxIngredients = 100

	# Nome: Lado de exibição
	# Descrição: Lado da tela para exibir a sobreposição do histórico de pesquisa.
	# Valores válidos: [LEFT, RIGHT]
	# Valor padrão: LEFT
	displaySide = LEFT


[advanced]
	# Nome: Capturar erros de renderização
	# Descrição: Captura erros de renderização de ingredientes modded e tenta se recuperar deles em vez de travar.
	# Valores válidos: [true, false]
	# Valor padrão: true
	catchRenderErrorsEnabled = true


[input]
	# Nome: Atraso de arraste
	# Descrição: Número de milissegundos antes que um clique longo do mouse seja considerado arrastar o mouse.
	# Valores válidos: An integer in the range [0, 1000] (inclusive)
	# Valor padrão: 150
	dragDelayInMilliseconds = 150

	# Nome: Taxa de rolagem suave
	# Descrição: Taxa de rolagem para rolar a roda do mouse em caixas de rolagem suave. Medido em pixels.
	# Valores válidos: An integer in the range [1, 50] (inclusive)
	# Valor padrão: 9
	smoothScrollRate = 9


[sorting]
	# Nome: Estágios de ordenação de ingredientes
	# Descrição: Ordem de classificação para a lista de ingredientes.
	# Valores válidos: A comma-separated list containing values of:
	# [MOD_NAME, INGREDIENT_TYPE, ALPHABETICAL, CREATIVE_MENU, TAG, ARMOR, MAX_DURABILITY]
	# Valor padrão: MOD_NAME, INGREDIENT_TYPE, CREATIVE_MENU
	ingredientSortStages = MOD_NAME, INGREDIENT_TYPE, CREATIVE_MENU

	# Nome: Estágios de ordenação de receitas
	# Descrição: Ordem de classificação para receitas exibidas.
	# Valores válidos: A comma-separated list containing values of:
	# [BOOKMARKED, CRAFTABLE]
	# Valor padrão: BOOKMARKED, CRAFTABLE
	recipeSorterStages = BOOKMARKED, CRAFTABLE


[search]
	# Nome: Modo de pesquisa por @Mod
	# Descrição: Modo de pesquisa para nomes de mods (prefixo: @).
	# Valores válidos: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valor padrão: REQUIRE_PREFIX
	modNameSearchMode = REQUIRE_PREFIX

	# Nome: Modo de pesquisa por #Tag
	# Descrição: Modo de pesquisa para tags (prefixo: #).
	# Valores válidos: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valor padrão: REQUIRE_PREFIX
	tagSearchMode = REQUIRE_PREFIX

	# Nome: Modo de pesquisa por $Tooltip
	# Descrição: Modo de pesquisa para dicas de ferramenta (prefixo: $).
	# Valores válidos: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valor padrão: ENABLED
	tooltipSearchMode = ENABLED

	# Nome: Modo de pesquisa por ^Cor
	# Descrição: Modo de pesquisa para cores (prefixo: ^).
	# Valores válidos: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valor padrão: DISABLED
	colorSearchMode = DISABLED

	# Nome: Modo de pesquisa por &Localização
	# Descrição: Modo de pesquisa para localizações de recursos (prefixo: &).
	# Valores válidos: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valor padrão: DISABLED
	resourceLocationSearchMode = DISABLED

	# Nome: Modo de pesquisa por %Aba criativa
	# Descrição: Modo de pesquisa para nomes de abas do modo criativo (prefixo: %).
	# Valores válidos: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valor padrão: DISABLED
	creativeTabSearchMode = DISABLED

	# Nome: Pesquisar dicas avançadas
	# Descrição: Pesquisa em dicas de ferramenta avançadas (visível com F3 + H).
	# Valores válidos: [true, false]
	# Valor padrão: false
	searchAdvancedTooltips = false

	# Nome: Pesquisar IDs de Mods
	# Descrição: Pesquisa IDs de mods além dos nomes dos mods.
	# Valores válidos: [true, false]
	# Valor padrão: true
	searchModIds = true

	# Nome: Pesquisar apelidos de mods
	# Descrição: Pesquisa apelidos de mods (nomes alternativos) que são adicionados por plugins, além dos nomes dos mods.
	# Valores válidos: [true, false]
	# Valor padrão: true
	searchModAliases = true

	# Nome: Pesquisar nomes curtos de mods
	# Descrição: Pesquisa pelas primeiras letras abreviadas do nome de um mod.
	# Valores válidos: [true, false]
	# Valor padrão: false
	searchShortModNames = false

	# Nome: Pesquisar apelidos de ingredientes
	# Descrição: Pesquisa apelidos de ingredientes (nomes alternativos) que são adicionados por plugins, além dos nomes dos ingredientes.
	# Valores válidos: [true, false]
	# Valor padrão: true
	searchIngredientAliases = true


[ingredientList]
	# Nome: Máximo de linhas
	# Descrição: Número máximo de linhas mostradas.
	# Valores válidos: An integer in the range [1, 100] (inclusive)
	# Valor padrão: 16
	maxRows = 16

	# Nome: Máximo de colunas
	# Descrição: Número máximo de colunas mostradas.
	# Valores válidos: An integer in the range [2, 100] (inclusive)
	# Valor padrão: 9
	maxColumns = 9

	# Nome: Alinhamento horizontal
	# Descrição: Alinhamento horizontal da lista de ingredientes dentro da área disponível.
	# Valores válidos: [LEFT, CENTER, RIGHT]
	# Valor padrão: RIGHT
	horizontalAlignment = RIGHT

	# Nome: Alinhamento vertical
	# Descrição: Alinhamento vertical da lista de ingredientes dentro da área disponível.
	# Valores válidos: [TOP, CENTER, BOTTOM]
	# Valor padrão: TOP
	verticalAlignment = TOP

	# Nome: Visibilidade da Navegação
	# Descrição: Visibilidade dos botões de página superiores. Use AUTO_HIDE para mostrar apenas quando houver várias páginas.
	# Valores válidos: [ENABLED, AUTO_HIDE, DISABLED]
	# Valor padrão: ENABLED
	buttonNavigationVisibility = ENABLED

	# Nome: Desenhar fundo da interface
	# Descrição: Habilite isso para desenhar uma textura de fundo atrás da lista de ingredientes.
	# Valores válidos: [true, false]
	# Valor padrão: false
	drawBackground = false


[bookmarkList]
	# Nome: Máximo de linhas
	# Descrição: Número máximo de linhas mostradas.
	# Valores válidos: An integer in the range [1, 100] (inclusive)
	# Valor padrão: 16
	maxRows = 16

	# Nome: Máximo de colunas
	# Descrição: Número máximo de colunas mostradas.
	# Valores válidos: An integer in the range [2, 100] (inclusive)
	# Valor padrão: 9
	maxColumns = 9

	# Nome: Alinhamento horizontal
	# Descrição: Alinhamento horizontal da lista de favoritos dentro da área disponível.
	# Valores válidos: [LEFT, CENTER, RIGHT]
	# Valor padrão: LEFT
	horizontalAlignment = LEFT

	# Nome: Alinhamento vertical
	# Descrição: Alinhamento vertical da lista de favoritos dentro da área disponível.
	# Valores válidos: [TOP, CENTER, BOTTOM]
	# Valor padrão: TOP
	verticalAlignment = TOP

	# Nome: Visibilidade da navegação
	# Descrição: Visibilidade dos botões de página superiores. Use AUTO_HIDE para mostrar apenas quando houver várias páginas.
	# Valores válidos: [ENABLED, AUTO_HIDE, DISABLED]
	# Valor padrão: ENABLED
	buttonNavigationVisibility = ENABLED

	# Nome: Desenhar fundo da interface
	# Descrição: Habilite isso para desenhar uma textura de fundo atrás da lista de favoritos.
	# Valores válidos: [true, false]
	# Valor padrão: false
	drawBackground = false


