[debug]
	# Nome: Modo de depuração
	# Descrição: Habilitar modo de depuração
	# Valores válidos: [true, false]
	# Valor padrão: false
	debugMode = false

	# Nome: Depurar interfaces
	# Descrição: Habilitar modo de depurar interfaces
	# Valores válidos: [true, false]
	# Valor padrão: false
	debugGuis = false

	# Nome: Depurar entradas
	# Descrição: Habilitar modo de depurar entradas
	# Valores válidos: [true, false]
	# Valor padrão: false
	debugInputs = false

	# Nome: Dicas de informações de depuração
	# Descrição: Adiciona informações de depuração às dicas de ferramenta de ingredientes quando as dicas avançadas estão habilitadas.
	# Valores válidos: [true, false]
	# Valor padrão: false
	debugInfoTooltipsEnabled = false

	# Nome: Habilitar itens de teste de travamento
	# Descrição: Adiciona ingredientes ao JEI que travam intencionalmente, para ajudar a depurar o JEI.
	# Valores válidos: [true, false]
	# Valor padrão: false
	crashingTestItemsEnabled = false

	# Nome: jei.config.debug.debug.crashingTestRecipesEnabled
	# Descrição: jei.config.debug.debug.crashingTestRecipesEnabled.description
	# Valores válidos: [true, false]
	# Valor padrão: false
	crashingTestRecipesEnabled = false

	# Nome: Logar estatísticas da árvore de sufixos
	# Descrição: Registra informações sobre as árvores de sufixos usadas para pesquisa, para ajudar a depurar o JEI.
	# Valores válidos: [true, false]
	# Valor padrão: false
	logSuffixTreeStats = false


