#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Sep 03 19:41:09 BRT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=13
shaderPack=ComplementaryUnbound_r5.7.1 + EuphoriaPatches_1.8.2
