#Todos os itens de configuração relacionados à jogabilidade principal
[gameplay]
	#Quantidade inicial de cidadãos. [Default: 4, min: 1, max: 10]
	# Default: 4
	# Range: 1 ~ 10
	initialcitizenamount = 4
	#Os jogadores deveriam poder posicionar uma quantidade infinita de acampamentos/navios de suprimentos? [Default: false]
	allowinfinitesupplychests = false
	#Os jogadores(as) são autorizados a abandonarem suas colônias para criar uma nova colônia facilmente? Nota: Isso é bugado! [Default: false]
	allowinfinitecolonies = false
	#É permitido criar colônias em outras dimensões? [Default: true]
	allowotherdimcolonies = true
	#Número máximo de cidadãos em uma colônia. [Default: 250, min: 25, max: 500]
	# Default: 250
	# Range: 25 ~ 500
	maxcitizenpercolony = 250
	#Funcionalidades em desenvolvimento devem ser habilitadas (pode haver bugs)? [Default: false]
	enableindevelopmentfeatures = false
	#Os nomes dos cidadãos devem ser renderizados? [Default: true]
	alwaysrendernametag = true
	#Trabalhadores devem trabalhar durante a chuva? [Default: false]
	workersalwaysworkinrain = false
	#Chance do Mineiro pegar um minério quando minerando pedregulho ou pedra (por padrão, pode ser expandido para outros materiais através de datapacks). Esta é uma porcentagem. (Para mudar quais minérios o Mineiro pode achar, veja "Lista de Minérios Raros".) [Default: 1, min: 0, max: 100]
	# Default: 1
	# Range: 0 ~ 100
	luckyblockchance = 1
	#O nível mínimo que a Prefeitura precisa estar para permitir teleporte para colônias aliadas. [Default: 3, min: 0, max: 5]
	# Default: 3
	# Range: 0 ~ 5
	minthleveltoteleport = 3
	#Modificador de consumo alimentar. [Default: 1.0, min: 0.1, max: 100.0]
	# Default: 1.0
	# Range: 0.1 ~ 100.0
	foodmodifier = 1.0
	#O quão comum uma doença é. 1 = muito comum, 100 = extremamente raro. [Default: 5, min: 1, max: 100]
	# Default: 5
	# Range: 1 ~ 100
	diseasemodifier = 5
	#Se parte da colônia for carregada por um proprietário / oficial, a colônia deve ser mantida carregada? (Defina quantos blocos são carregados com a opção "Estrita de carregamento de blocos da colônia".) [Default: true]
	forceloadcolony = true
	#Define por quanto tempo os chunks permanecem carregados após a saída do jogador, não persiste através de reinicializações. Padrão: 10min [Default: 20, min: 1, max: 1440]
	# Default: 20
	# Range: 1 ~ 1440
	loadtime = 20
	#Isso controla quantos pedaços são carregados com a opção "Carregamento de regiões da Colônia". Quanto mais alto esse valor, menos blocos serão carregados. (Os blocos mais internos serão carregados primeiro.) 1 = carregue todos os blocos reivindicados. [Default: 3, min: 1, max: 15]
	# Default: 3
	# Range: 1 ~ 15
	colonyloadstrictness = 3
	#Contagem máxima de toras em uma árvore para o Lenhador(a) verificar durante a busca na árvore. [Default: 400, min: 1, max: 1000]
	# Default: 400
	# Range: 1 ~ 1000
	maxtreesize = 400
	#Desativa as restrições de posicionamento do acampamento de suprimentos, destinado a mundos celestes e similares [Default: false]
	nosupplyplacementrestrictions = false
	#Invasores surgirão no céu se isto estiver habilitado [Default: false]
	skyraiders = false

#Todas as configurações relacionadas ao sistema de solicitações
[research]
	#Permite a conclusão automática e (quase) instantânea da pesquisa para os jogadores no modo criativo. Se for falso, os jogadores criativos ainda poderão iniciar pesquisas, mas terão taxas de progresso normais. [Default: true]
	researchcreativecompletion = true
	#Aumenta significativamente a quantidade de informações relacionadas a datapacks de pesquisa que são registradas durante o carregamento mundial. [Default: false]
	researchdebuglog = false
	#Uma lista de itens para cobrar dos jogadores ao desfazer uma pesquisa já concluída.
	researchresetcost = ["minecolonies:ancienttome:1"]

#Todas as configurações relacionadas aos comandos do MineColonies
[commands]
	#É permitido que os jogadores usem o comando /mc rtp? [Default: false]
	canplayerusertpcommand = false
	#É permitido que os jogadores usem o comando "/mc colony teleport"? [Default: false]
	canplayerusecolonytpcommand = false
	#Jogadores podem teleportar para colônias aliadas? [Default: true]
	canplayeruseallytownhallteleport = true
	#É permitido que os jogadores usem o comando /mc home? Nota: Apenas donos de colônia podem usar este comando. [Default: false]
	canplayerusehometpcommand = false
	#É permitido que os jogadores usem o comando /mc colony indo? [Default: true]
	canplayeruseshowcolonyinfocommand = true
	#É permitido que os jogadores usem o comando /mc citizens kill? [Default: false]
	canplayerusekillcitizenscommand = false
	#Os jogadores devem ser autorizados a usar o comando /mc citizens modify? [Default: false]
	canplayerusemodifycitizenscommand = false
	#É permitido que os jogadores usem o comando /mc colony addOfficer? [Default: true]
	canplayeruseaddofficercommand = true
	#É permitido que os jogadores usem o comando /mc colony delete? [Default: false]
	canplayerusedeletecolonycommand = false
	#É permitido que os jogadores usem o comando /mc colony requestsystem-reset? [Default: false]
	canplayeruseresetcommand = false

#Todas as configurações relacionadas às reivindicações da colônia
[claims]
	#minecolonies.config.maxColonySize.comment [Default: 20, min: 1, max: 250]
	# Default: 20
	# Range: 1 ~ 250
	maxColonySize = 20
	#minecolonies.config.minColonyDistance.comment [Default: 8, min: 1, max: 200]
	# Default: 8
	# Range: 1 ~ 200
	minColonyDistance = 8
	#minecolonies.config.initialColonySize.comment [Default: 4, min: 1, max: 15]
	# Default: 4
	# Range: 1 ~ 15
	initialColonySize = 4
	#Maxima distância (em blocos) do ponto de geração do mundo e uma colônia. [Default: 30000, min: 1000, max: 2147483647]
	# Default: 30000
	# Range: > 1000
	maxdistancefromworldspawn = 30000
	#Mínima distância (em blocos) do ponto de geração do mundo e uma colônia. [Default: 0, min: 0, max: 1000]
	# Default: 0
	# Range: 0 ~ 1000
	mindistancefromworldspawn = 0

#Todas as configurações relacionadas aos elementos de combate do MineColonies
[combat]
	#minecolonies.config.dobarbariansspawn.comment [Default: true]
	dobarbariansspawn = true
	#minecolonies.config.barbarianhordedifficulty.comment [Default: 5, min: 0, max: 10]
	# Default: 5
	# Range: 0 ~ 10
	barbarianhordedifficulty = 5
	#minecolonies.config.maxBarbarianSize.comment [Default: 80, min: 6, max: 400]
	# Default: 80
	# Range: 6 ~ 400
	maxBarbarianSize = 80
	#minecolonies.config.dobarbariansbreakthroughwalls.comment [Default: true]
	dobarbariansbreakthroughwalls = true
	#O número médio de noites entre ataques. [Default: 14, min: 1, max: 50]
	# Default: 14
	# Range: 1 ~ 50
	averagenumberofnightsbetweenraids = 14
	#A quantidade mínima de noites entre ataques. [Default: 10, min: 1, max: 30]
	# Default: 10
	# Range: 1 ~ 30
	minimumnumberofnightsbetweenraids = 10
	#Monstros devem atacar cidadãos? [Default: true]
	mobattackcitizens = true
	#minecolonies.config.shouldraiderbreakdoors.comment [Default: true]
	shouldraiderbreakdoors = true
	#Multiplicador do dano causado por Guardas. [Default: 1.0, min: 0.1, max: 15.0]
	# Default: 1.0
	# Range: 0.1 ~ 15.0
	guardDamageMultiplier = 1.0
	#Multiplicador de saúde para todos os Guardas. [Default: 1.0, min: 0.1, max: 5.0]
	# Default: 1.0
	# Range: 0.1 ~ 5.0
	guardhealthmult = 1.0
	#Habilite o modo PVP de MineColonies (colônias podem ser destruídas ou vandalizadas em certas condições). [Default: false]
	pvp_mode = false

#Todas as Configurações de Permissão
[permissions]
	#A proteção de colônia deve ser ativada? [Default: true]
	enablecolonyprotection = true
	#Independente da proteção das colônias, as explosões devem ser desligadas dentro das colônias? DAMAGE_NOTHING evitar explosões completamente. DAMAGE_PLAYERS, permite que explosões causem dano a jogadores e mobs hostis, mas não protege mobs neutros ou amigáveis. DAMAGE_ENTITIES permite danos a todas as entidades. DAMAGE_EVERYTHING permite que explosões danifiquem entidades e blocos. [Default: DAMAGE_ENTITIES, values: DAMAGE_NOTHING, DAMAGE_PLAYERS, DAMAGE_ENTITIES, DAMAGE_EVERYTHING]
	#Allowed Values: DAMAGE_NOTHING, DAMAGE_PLAYERS, DAMAGE_ENTITIES, DAMAGE_EVERYTHING
	turnoffexplosionsincolonies = "DAMAGE_ENTITIES"
	#Desabilita permissões da colônia se o jogador tiver um determinado nível de permissão. [Default: 2, min: 0, max: 4]
	# Default: 2
	# Range: 0 ~ 4
	permissioneventbypassminpermlevel = 2

#Todas as configurações relacionadas a compatibilidade do mod
[compatibility]
	#Ao carregar receitas, gere arquivos CSV de auditoria para ajudar a depurar pacotes de dados ou modificações extras. [Default: false]
	auditcraftingtags = false
	#Habilitar conserto de bugs no inventário. [Default: false]
	debuginventories = false
	#Ative essa função se esse mapa é somente para testes de construção e exportação de modelos. [Default: false]
	blueprintbuildmode = false
	#Aumenta o limite de nós de busca de caminhos pelo fator especificado, permitindo que os cidadãos pesquisem uma área maior, ao custo de desempenho (fora da thread), para uma busca de caminhos mais precisa. [Default: 1.0, min: 1.0, max: 4.0]
	# Default: 1.0
	# Range: 1.0 ~ 4.0
	pathNodeLimitMultiplier = 1.0
	#Número mínimo de trilhos consecutivos para os cidadãos os usarem. [Default: 8, min: 5, max: 100]
	# Default: 8
	# Range: 5 ~ 100
	minimumrailstopath = 8

#minecolonies.config.requestSystem.comment
[requestSystem]
	#O sistema de solicitação deve resolver criativamente (se possível) quando o jogador é solicitado a resolver uma solicitação? Esta é uma ferramenta de depuração e pode levar muito tempo para resolver uma solicitação. [Default: false]
	creativeresolve = false
