# Browser client config (Win64 WebView2 preferred)
homepage=https://docs.qq.com/aio/p/scjg6678qvr4qq3
webview2.block_new_windows=true
webview2.remove_workbench_titlebar=true
webview2.remove_transition_space=true
startup.force_first_open_url=true
startup.first_open_url=https://docs.qq.com/aio/p/scjg6678qvr4qq3
