["Boss Health"]
	#Max Health : 1024
	"Sandworm Health" = 450.0
	"Yeti Health" = 400.0
	"Dragon Health" = 850.0
	"Knight Health" = 500.0
	"Kraken Health" = 950.0

["Boss Armor"]
	#Max Armor : 30
	"Sandworm Armor" = 20.0
	"Yeti Armor" = 15.0
	"Dragon Armor" = 30.0
	"Knight Armor" = 22.0
	"Kraken Armor" = 25.0

["Base Boss Damages"]
	#Not all damages sources depends on this variable !
	"Sandworm Damage" = 28.0
	"Yeti Damage" = 32.0
	"Dragon Damage" = 15.0
	"Knight Damage" = 30.0
	"Kraken Damage" = 35.0

["Gameplay Changes"]
	"Can players use the Roll ability" = true
	"How many roll charges does the player have by default?" = 2
	"How many ticks does it take for a roll to cooldown? (20 ticks is 1 second)" = 40
	"How many additional ticks should each roll above 1 take to cooldown? (20 ticks is 1 second)" = 20
