#Startup Settings
[startupSettings]
	#Adds new JNE inspired splash texts alongside the vanilla ones if enabled
	enableJNESplashTexts = true
	#Splash texts added by JNE will be a wonderful red color opposed to the usual yellow
	redSplashText = true
	#JNE has swearing, and lots of it too but is normally censored 
	#If you'd like to disable profanity entirely or uncensor it you may do so with this config
	#Allowed Values: DISABLED, CENSORED, UNFILTERED
	profanity = "CENSORED"

#Pack Settings
[packSettings]
	#Changes the soot part of the soul campfire texture to become soul soil instead
	soulCampfireSoulSoil = true
