#Client side VFX render toggles. These only affect this Minecraft client.
[vfx]
	#If false, all Tensura More Skills VFX are disabled on this client.
	allEffects = true

	[vfx.effects]
		albis_vina = true
		asmoday_black_hole = true
		asmoday_falling_cube = true
		asmoday_prison_realm = true
		asmoday_space = true
		asmoday_spatial_absorption = true
		asmoday_spatial_cube = true
		avalon_novari_phase = true
		axis_judgment = true
		black_blood_domain_fog = true
		black_communion = true
		chrono_judgement_clock = true
		elfaria_albis_ice_sheet = true
		elfaria_ares_weiss_bloom = true
		elfaria_fruzel_cardeneia = true
		elfaria_glacial_last_albis = true
		elfaria_icemaiden = true
		elfaria_myrdas_fridolet = true
		elfaria_oplce_shine = true
		elfaria_passive_ice_steps = true
		elfaria_stellas_natea = true
		elfaria_vfx_helper = true
		elfaria_vfx_vertex_helper = true
		exploiter_xray_hook = true
		feldway_avatar_beam = true
		feldway_awakening_block_storm = true
		feldway_awakening_camera_shake = true
		feldway_awakening_coronation_beam = true
		feldway_awakening_shader = true
		feldway_reward_client_fx = true
		full_cowl_lightning = true
		gearshift_blue_trail = true
		imperial_halo_shot = true
		istaroth_camera_shake = true
		istaroth_doom_tornado = true
		istaroth_gray_shader = true
		istaroth_screen_fx = true
		i_want_limbo = true
		michael_aura = true
		michael_halberd_shot = true
		michael_jerez = true
		michael_keter = true
		michael_lataib_barrage = true
		michael_segva = true
		michael_shifuru_meteor = true
		michael_vfx = true
		mitama_atomic_edict = true
		mitama_divine_beams = true
		novari_black_white = true
		pain_planetary_devastation = true
		pain_six_paths = true
		phainon_acquirement = true
		ronova_finality = true
		satella = true
		seraphic_guillotine = true
		witch_of_envy_satella = true
