#Protect every mob (including non-subordinate/pet) from tensura abilities in non-pvp claims.
protectMobs = true
#Should FTB teams members to be counted as Ally for Tensura's abilities.
ftbAllyTensura = true
#Allow possession in non-pvp claims.
possession = false
#Allow mind controlling in non-pvp claims.
mindControl = false
#Allow spiritual damage in non-pvp claims.
spiritualDamage = false
#Protect players from tensura abilities in non-pvp claims.
protectPlayers = true
#Protect subordinates/pets from tensura abilities in non-pvp claims.
protectSubordinates = true
#Allow energy draining in non-pvp claims.
energyDrain = false
#Allow movement forced by others' abilities in non-pvp claims.
forcedMovement = false
#Allow non-ability damage (normal weapon swing, arrow, etc) from others to damage non-player protected mobs in non-pvp claims.
mobDamage = false
#Allow ability griefing in claimed chunks.
abilityGrief = false
#Allow teleportation forced by others' abilities in non-pvp claims.
forcedTeleportation = false
#Allow harmful effect from others to be inflicted in non-pvp claims.
harmfulEffect = false
#Allow ability plundering in non-pvp claims.
abilityPlundering = false
#Allow ability damage from others to damage non-player protected mobs in non-pvp claims.
mobDamageAbility = false
#List of entities that are automatically protected from tensura abilities in non-pvp claims regardless of their entity type.
protectedEntities = ["minecraft:villager", "tensura:dwarf"]
