#Spawn probability for mobs (1 in X chance). First value is Day, Second is Night.
#Examples: 1=100%, 5=20%, 10=10%. 0=disabled.
[SpawnChance]
	#One of how many chances for Memoires to spawn.
	memoiresChance = 1000
	#One of how many chances for an Okami to spawn.
	okamiChance = 8
