#Controls if Tensura HUD elements should be rendered at all or not
tensuraHud = true
#Controls if Vanilla HUD elements should be rendered at all or not
vanillaHud = false

[status]
	#Ignored if defaultRendering is true
	positionX = 0.0
	positionY = 0.0
	#The multiplier for the element size
	#Scales all other elements that have defaultRendering set to true except Abilities and Analysis0.0 ~ Any
	scale = 1.0
	#Setting to 1 will make the element to render from left to right and vice versa if 2
	#Setting to 0 will allow the renderer to decide dynamically
	#Will also move other elements that have defaultRendering set to true
	#
	#0 ~ 2
	side = 0
	#Separate check if this specific element should render
	#Ignored if tensuraHud = false
	render = true
	#If true, dynamically adjusts the element
	defaultRendering = true

	#Properties notes:
	#positionX = Horizontal position; Ignored if defaultRendering is true
	#positionY = Vertical position; Ignored if defaultRendering is true
	#side = 0 means dynamic rendering, 1 makes it render from left to right, 2 mirrors it; Ignored if defaultRendering is true
	#0 ~ 2
	#scale = Size multiplier for the element, such as 0.8 or 1.2; Uses Status's scale if defaultRendering is true
	#0.05 ~ 5
	#render = Separate check if the element should render; Ignored if tensuraHud is false
	#defaultRendering = Dynamically adjust everything
	[decorations.air]
		positionX = 0.0
		positionY = 0.0
		side = 0
		scale = 1.0
		render = true
		defaultRendering = true

	[decorations.food]
		positionX = 0.0
		positionY = 0.0
		side = 0
		scale = 1.0
		render = true
		defaultRendering = true

	[decorations.armor]
		positionX = 0.0
		positionY = 0.0
		side = 0
		scale = 1.0
		render = true
		defaultRendering = true

	[decorations.barrier]
		positionX = 0.0
		positionY = 0.0
		side = 0
		scale = 1.0
		render = true
		defaultRendering = true

	[decorations.mountHp]
		positionX = 0.0
		positionY = 0.0
		side = 0
		scale = 1.0
		render = true
		defaultRendering = true

	[decorations.mountSpiritualHp]
		positionX = 0.0
		positionY = 0.0
		side = 0
		scale = 1.0
		render = true
		defaultRendering = true

[statusBars]
	#Ignored if defaultRendering is true
	positionX = 0.0
	positionY = 0.0
	#The multiplier for the element size
	#Uses Status's scale if defaultRendering is true
	#0.05 ~ 5
	scale = 1.0
	#Setting to 1 will force the element to render from left to right and vice versa if 2
	#Uses Status's side if defaultRendering is true
	#0 ~ 2
	side = 0
	#Separate check if this specific element should render
	#Ignored if tensuraHud = false
	render = true
	#If true, dynamically adjusts the element
	defaultRendering = true

[abilities]
	#Ignored if defaultRendering is true
	positionX = 0.0
	positionY = 90.45559
	#The multiplier for the element size
	#0.05 ~ 5
	scale = 1.0
	#Setting to 1 will make the element to render from left to right and vice versa if 2
	#Setting to 0 will allow the renderer to decide dynamically
	#0 ~ 2
	side = 0
	#Separate check if this specific element should render
	#Ignored if tensuraHud = false
	render = true
	#If true, dynamically adjusts the element
	defaultRendering = false

[analysis]
	#Ignored if defaultRendering is true
	positionX = 417.0
	positionY = 55.75092
	#The multiplier for the element size
	#0.05 ~ 5
	scale = 0.8
	#How opaque the element should be when rendering
	#0.0 ~ 1.0
	opacity = 1.0
	#Setting to 1 will make the element to render from left to right and vice versa if 2
	#Setting to 0 will allow the renderer to decide dynamically
	#0 ~ 2
	side = 2
	#Separate check if this specific element should render
	#Ignored if tensuraHud = false
	render = true
	#If true, dynamically adjusts the element
	defaultRendering = true
	#If true, will render target's hearts instead of HP (1 heart = 2 HP)
	useHearts = true
