[Centipede]
	#Minimal aura.
	minAura = 1000.0
	#Maximum aura.
	maxAura = 2000.0
	#Minimal magicule.
	minMagicule = 2000.0
	#Maximum magicule.
	maxMagicule = 3000.0
	#Bonus Size.
	size = -0.75
	#Bonus Max Health.
	maxHealth = 4.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 35.0
	#Bonus Attack Damage.
	attack = 0.5
	#Bonus Attack Speed.
	attackSpeed = 0.0
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.30000001192092896
	#Bonus Swimming Speed Multiplier.
	swimSpeed = -0.5
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis"]

[BlueCentipede]
	#EP requirement to evolve into Blue Centipede.
	epRequirement = 10000.0
	#Minimal aura.
	minAura = 5250.0
	#Maximum aura.
	maxAura = 5250.0
	#Minimal magicule.
	minMagicule = 5250.0
	#Maximum magicule.
	maxMagicule = 5250.0
	#Bonus Size.
	size = -0.6000000238418579
	#Bonus Max Health.
	maxHealth = 15.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 60.0
	#Bonus Attack Damage.
	attack = 1.0
	#Bonus Attack Speed.
	attackSpeed = 0.0
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.30000001192092896
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 1.0
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis"]

[BlueCentipedeInsectar]
	#EP requirement to evolve into Blue Centipede Insectar.
	epRequirement = 100000.0
	#Minimal aura.
	minAura = 100000.0
	#Maximum aura.
	maxAura = 100000.0
	#Minimal magicule.
	minMagicule = 100000.0
	#Maximum magicule.
	maxMagicule = 100000.0
	#Bonus Size.
	size = -0.20000000298023224
	#Bonus Max Health.
	maxHealth = 105.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 700.0
	#Bonus Attack Damage.
	attack = 1.5
	#Bonus Attack Speed.
	attackSpeed = 0.0
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.33000001311302185
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 1.2999999523162842
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis"]

[BlueCentipedeSavant]
	#EP requirement to evolve into Blue Centipede Savant.
	epRequirement = 400000.0
	#The number of Bosses defeated to evolve into Blue Centipede Savant.
	bossRequirement = 4
	#Minimal aura.
	minAura = 400000.0
	#Maximum aura.
	maxAura = 400000.0
	#Minimal magicule.
	minMagicule = 400000.0
	#Maximum magicule.
	maxMagicule = 400000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 425.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 1250.0
	#Bonus Attack Damage.
	attack = 2.0
	#Bonus Attack Speed.
	attackSpeed = 0.0
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.3499999940395355
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 1.7999999523162842
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis"]

[WaterSoulInsect]
	#EP requirement to evolve into Water Soul Insect.
	epRequirement = 400000.0
	#The ability needed to evolve into Water Soul Insect.
	abilityRequirement = "tensura:water_manipulation"
	#Minimal aura.
	minAura = 400000.0
	#Maximum aura.
	maxAura = 400000.0
	#Minimal magicule.
	minMagicule = 400000.0
	#Maximum magicule.
	maxMagicule = 400000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 355.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 1630.0
	#Bonus Attack Damage.
	attack = 1.75
	#Bonus Attack Speed.
	attackSpeed = 0.0
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.33000001311302185
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 2.0
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis", "tensura:water_manipulation", "tensura:water_attack_resistance", "tensura:water_transform"]

[DivineBlueCentipede]
	#EP requirement to evolve into Divine Blue Centipede.
	epRequirement = 2000000.0
	#Minimal aura.
	minAura = 1000000.0
	#Maximum aura.
	maxAura = 1000000.0
	#Minimal magicule.
	minMagicule = 1000000.0
	#Maximum magicule.
	maxMagicule = 1000000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 930.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 6240.0
	#Bonus Attack Damage.
	attack = 2.5
	#Bonus Attack Speed.
	attackSpeed = 0.0
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.4000000059604645
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 2.5
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis", "tensura:divine_ki_release"]

[YellowCentipede]
	#EP requirement to evolve into Yellow Centipede.
	epRequirement = 10000.0
	#Minimal aura.
	minAura = 5250.0
	#Maximum aura.
	maxAura = 5250.0
	#Minimal magicule.
	minMagicule = 5250.0
	#Maximum magicule.
	maxMagicule = 5250.0
	#Bonus Size.
	size = -0.6000000238418579
	#Bonus Max Health.
	maxHealth = 12.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 55.0
	#Bonus Attack Damage.
	attack = 1.5
	#Bonus Attack Speed.
	attackSpeed = 0.20000000298023224
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.3499999940395355
	#Bonus Swimming Speed Multiplier.
	swimSpeed = -0.4000000059604645
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis"]

[YellowCentipedeInsectar]
	#EP requirement to evolve into Yellow Centipede Insectar.
	epRequirement = 100000.0
	#Minimal aura.
	minAura = 100000.0
	#Maximum aura.
	maxAura = 100000.0
	#Minimal magicule.
	minMagicule = 100000.0
	#Maximum magicule.
	maxMagicule = 100000.0
	#Bonus Size.
	size = -0.20000000298023224
	#Bonus Max Health.
	maxHealth = 95.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 630.0
	#Bonus Attack Damage.
	attack = 2.0
	#Bonus Attack Speed.
	attackSpeed = 0.2750000059604645
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.4000000059604645
	#Bonus Swimming Speed Multiplier.
	swimSpeed = -0.30000001192092896
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis"]

[YellowCentipedeSavant]
	#EP requirement to evolve into Yellow Centipede Savant.
	epRequirement = 400000.0
	#The number of Bosses defeated to evolve into Yellow Centipede Savant.
	bossRequirement = 4
	#Minimal aura.
	minAura = 400000.0
	#Maximum aura.
	maxAura = 400000.0
	#Minimal magicule.
	minMagicule = 400000.0
	#Maximum magicule.
	maxMagicule = 400000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 330.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 1130.0
	#Bonus Attack Damage.
	attack = 3.0
	#Bonus Attack Speed.
	attackSpeed = 0.3499999940395355
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.44999998807907104
	#Bonus Swimming Speed Multiplier.
	swimSpeed = -0.20000000298023224
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis"]

[ParalysisSoulInsect]
	#EP requirement to evolve into Paralysis Soul Insect.
	epRequirement = 400000.0
	#The ability needed to evolve into Paralysis Soul Insect.
	abilityRequirement = "tensura:ranged_barrier"
	#Minimal aura.
	minAura = 400000.0
	#Maximum aura.
	maxAura = 400000.0
	#Minimal magicule.
	minMagicule = 400000.0
	#Maximum magicule.
	maxMagicule = 400000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 280.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 1520.0
	#Bonus Attack Damage.
	attack = 2.5
	#Bonus Attack Speed.
	attackSpeed = 0.30000001192092896
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.42500001192092896
	#Bonus Swimming Speed Multiplier.
	swimSpeed = -0.25
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis", "tensura:paralysis_resistance", "mysticism:paralysis_transform"]

[DivineYellowCentipede]
	#EP requirement to evolve into Divine Yellow Centipede.
	epRequirement = 2000000.0
	#Minimal aura.
	minAura = 1000000.0
	#Maximum aura.
	maxAura = 1000000.0
	#Minimal magicule.
	minMagicule = 1000000.0
	#Maximum magicule.
	maxMagicule = 1000000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 880.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 5980.0
	#Bonus Attack Damage.
	attack = 4.0
	#Bonus Attack Speed.
	attackSpeed = 0.4000000059604645
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.5
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.0
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis", "tensura:divine_ki_release"]

[PurpleCentipede]
	#EP requirement to evolve into Purple Centipede.
	epRequirement = 10000.0
	#Minimal aura.
	minAura = 5250.0
	#Maximum aura.
	maxAura = 5250.0
	#Minimal magicule.
	minMagicule = 5250.0
	#Maximum magicule.
	maxMagicule = 5250.0
	#Bonus Size.
	size = -0.6000000238418579
	#Bonus Max Health.
	maxHealth = 14.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 50.0
	#Bonus Attack Damage.
	attack = 1.0
	#Bonus Attack Speed.
	attackSpeed = 0.20000000298023224
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.029999999329447746
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.0
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis"]

[PurpleCentipedeInsectar]
	#EP requirement to evolve into Purple Centipede Insectar.
	epRequirement = 100000.0
	#Minimal aura.
	minAura = 100000.0
	#Maximum aura.
	maxAura = 100000.0
	#Minimal magicule.
	minMagicule = 100000.0
	#Maximum magicule.
	maxMagicule = 100000.0
	#Bonus Size.
	size = -0.20000000298023224
	#Bonus Max Health.
	maxHealth = 100.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 630.0
	#Bonus Attack Damage.
	attack = 1.5
	#Bonus Attack Speed.
	attackSpeed = 0.6000000238418579
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.029999999329447746
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.0
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis"]

[PurpleCentipedeSavant]
	#EP requirement to evolve into Purple Centipede Savant.
	epRequirement = 400000.0
	#The number of Bosses defeated to evolve into Purple Centipede Savant.
	bossRequirement = 4
	#Minimal aura.
	minAura = 400000.0
	#Maximum aura.
	maxAura = 400000.0
	#Minimal magicule.
	minMagicule = 400000.0
	#Maximum magicule.
	maxMagicule = 400000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 380.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 1130.0
	#Bonus Attack Damage.
	attack = 1.75
	#Bonus Attack Speed.
	attackSpeed = 0.800000011920929
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.029999999329447746
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.0
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis"]

[SpatialSoulInsect]
	#EP requirement to evolve into Spatial Soul Insect.
	epRequirement = 400000.0
	#The ability needed to evolve into Spatial Soul Insect.
	abilityRequirement = "tensura:spatial_manipulation"
	#Minimal aura.
	minAura = 400000.0
	#Maximum aura.
	maxAura = 400000.0
	#Minimal magicule.
	minMagicule = 400000.0
	#Maximum magicule.
	maxMagicule = 400000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 355.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 1480.0
	#Bonus Attack Damage.
	attack = 1.5
	#Bonus Attack Speed.
	attackSpeed = 0.699999988079071
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.029999999329447746
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.0
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis", "tensura:spatial_manipulation", "tensura:spatial_attack_resistance", "tensura:space_transform"]

[DivinePurpleCentipede]
	#EP requirement to evolve into Divine Purple Centipede.
	epRequirement = 2000000.0
	#Minimal aura.
	minAura = 1000000.0
	#Maximum aura.
	maxAura = 1000000.0
	#Minimal magicule.
	minMagicule = 1000000.0
	#Maximum magicule.
	maxMagicule = 1000000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 930.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 6230.0
	#Bonus Attack Damage.
	attack = 2.0
	#Bonus Attack Speed.
	attackSpeed = 1.0
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.029999999329447746
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.0
	#The list of intrinsic skills that the race gets.
	intrinsicSkills = ["mysticism:exoskeleton", "tensura:analytical_appraisal", "tensura:paralysis", "tensura:divine_ki_release"]
