[Beastfolk]
	#Minimal aura.
	minAura = 1500.0
	#Maximum aura.
	maxAura = 2500.0
	#Minimal magicule.
	minMagicule = 300.0
	#Maximum magicule.
	maxMagicule = 600.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 2.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 10.0
	#Bonus Attack Damage.
	attack = 0.0
	#Bonus Attack Speed.
	attackSpeed = 0.1
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = 0.05
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.5

[BeastLord]
	#EP requirement to evolve into Beast Lord.
	epRequirement = 100000.0
	#Minimal aura.
	minAura = 100000.0
	#Maximum aura.
	maxAura = 100000.0
	#Minimal magicule.
	minMagicule = 100000.0
	#Maximum magicule.
	maxMagicule = 100000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 140.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 440.0
	#Bonus Attack Damage.
	attack = 3.0
	#Bonus Attack Speed.
	attackSpeed = 0.3
	#Bonus Knockback Resistance.
	knockbackResistance = 0.1
	#Bonus Movement Speed.
	movementSpeed = 0.06
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.7

[SpiritBeast]
	#EP requirement to evolve into Spirit Beast.
	epRequirement = 400000.0
	#The number of Bosses defeated to evolve into Spirit Beast.
	bossRequirement = 4
	#Minimal aura.
	minAura = 400000.0
	#Maximum aura.
	maxAura = 400000.0
	#Minimal magicule.
	minMagicule = 400000.0
	#Maximum magicule.
	maxMagicule = 400000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 580.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 6340.0
	#Bonus Attack Damage.
	attack = 4.0
	#Bonus Attack Speed.
	attackSpeed = 0.6
	#Bonus Knockback Resistance.
	knockbackResistance = 0.2
	#Bonus Movement Speed.
	movementSpeed = 0.1
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 1.0

[DivineBeast]
	#EP requirement to evolve into Divine Beast.
	epRequirement = 2000000.0
	#Minimal aura.
	minAura = 1000000.0
	#Maximum aura.
	maxAura = 1000000.0
	#Minimal magicule.
	minMagicule = 1000000.0
	#Maximum magicule.
	maxMagicule = 1000000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 1180.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 7940.0
	#Bonus Attack Damage.
	attack = 7.0
	#Bonus Attack Speed.
	attackSpeed = 0.9
	#Bonus Knockback Resistance.
	knockbackResistance = 0.3
	#Bonus Movement Speed.
	movementSpeed = 0.12
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 1.2
