[Merfolk]
	#Minimal aura.
	minAura = 400.0
	#Maximum aura.
	maxAura = 600.0
	#Minimal magicule.
	minMagicule = 500.0
	#Maximum magicule.
	maxMagicule = 600.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 4.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 20.0
	#Bonus Attack Damage.
	attack = 0.0
	#Bonus Attack Speed.
	attackSpeed = 0.0
	#Bonus Knockback Resistance.
	knockbackResistance = 0.0
	#Bonus Movement Speed.
	movementSpeed = -0.01
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.5
	#Bonus Submerged Mining Speed.
	submergedMiningSpeed = 0.4

[EnlightenedMerfolk]
	#EP requirement to evolve into Enlightened Merfolk.
	epRequirement = 100000.0
	#Minimal aura.
	minAura = 140000.0
	#Maximum aura.
	maxAura = 140000.0
	#Minimal magicule.
	minMagicule = 60000.0
	#Maximum magicule.
	maxMagicule = 60000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 100.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 320.0
	#Bonus Attack Damage.
	attack = 1.0
	#Bonus Attack Speed.
	attackSpeed = 0.2
	#Bonus Knockback Resistance.
	knockbackResistance = 0.05
	#Bonus Movement Speed.
	movementSpeed = 0.01
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 0.7
	#Bonus Submerged Mining Speed.
	submergedMiningSpeed = 0.6

[MerfolkSaint]
	#EP requirement to evolve into Merfolk Saint.
	epRequirement = 400000.0
	#The number of Bosses defeated to evolve into Merfolk Saint.
	bossRequirement = 4
	#Minimal aura.
	minAura = 400000.0
	#Maximum aura.
	maxAura = 400000.0
	#Minimal magicule.
	minMagicule = 400000.0
	#Maximum magicule.
	maxMagicule = 400000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 520.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 3140.0
	#Bonus Attack Damage.
	attack = 2.0
	#Bonus Attack Speed.
	attackSpeed = 0.5
	#Bonus Knockback Resistance.
	knockbackResistance = 0.1
	#Bonus Movement Speed.
	movementSpeed = 0.05
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 1.0
	#Bonus Submerged Mining Speed.
	submergedMiningSpeed = 0.8

[DivineFish]
	#EP requirement to evolve into Divine Fish.
	epRequirement = 2000000.0
	#Minimal aura.
	minAura = 1000000.0
	#Maximum aura.
	maxAura = 1000000.0
	#Minimal magicule.
	minMagicule = 1000000.0
	#Maximum magicule.
	maxMagicule = 1000000.0
	#Bonus Size.
	size = 0.0
	#Bonus Max Health.
	maxHealth = 1040.0
	#Bonus Max Spiritual Health.
	maxSpiritualHealth = 6140.0
	#Bonus Attack Damage.
	attack = 3.0
	#Bonus Attack Speed.
	attackSpeed = 0.7
	#Bonus Knockback Resistance.
	knockbackResistance = 0.2
	#Bonus Movement Speed.
	movementSpeed = 0.1
	#Bonus Swimming Speed Multiplier.
	swimSpeed = 1.5
	#Bonus Submerged Mining Speed.
	submergedMiningSpeed = 1.0
