[SpecialVariant]
	#One of how many chances for an otherworlder to spawn as Shizu.
	shizuChance = 30
	#One of how many chances for an otherworlder to spawn as Hinata Sakaguchi.
	hinataChance = 69
	#One of how many chances for a hell caterpillar to spawn as a gehenna caterpillar.
	gehennaCaterpillarChance = 20
	#One of how many chances for a hell caterpillar cocoon to mutate to a gehenna moth.
	gehennaCocoonChance = 60
	#One of how many chances for a hell moth to spawn as or evolve to a gehenna moth.
	gehennaMothChance = 20
	#One of how many chances for a hound dog to have a snake tail.
	houndDogSnakeChance = 20
	#One of how many chances for an orc to be an orc lord.
	orcLordChance = 900
	#One of how many chances for an orc to be a royal orc.
	orcRoyalChance = 100
	#One of how many chances for a Royal Orc to have Self-Regeneration.
	orcRoyalLordChance = 7
	#One of how many chances for a Direwolf to be an Alpha.
	alphaWolf = 10
	#One of how many chances for a Tempest Wolf to have the Star birthmark.
	starBirthmark = 8
	#The percentage chance for a direwolf pack to be evolved
	evolvedPack = 40
	#The percentage chance for a direwolf pack to be Elemental Fang based on biomes
	elementalFangPack = 65
	#The percentage chance for a direwolf pack to be Tempest Wolves
	tempestWolfPack = 10
	#One of how many chances for a slime to spawn as Metal Slime.
	metalSlimeChance = 500
	#One of how many chances for a slime to spawn as Supermassive Slime.
	supermassiveSlimeChance = 1000
	#One of how many chances for a medium spirit spawned in Ancient Forest to spawn as a greater spirit.
	greaterSpiritChance = 600

#Spawn probability for mobs (1 in X chance). First value is Day, Second is Night.
#Examples: 1=100%, 5=20%, 10=10%. 0=disabled.
[SpawnChance]
	otherworlder = [60, 30]
	aquaFrog = [16, 8]
	armorsaurus = [4, 2]
	armyWasp = [11, 8]
	barghest = [7, 5]
	basilisk = [10, 7]
	beastGnome = [16, 8]
	blackSpider = [8, 5]
	bladeTiger = [8, 6]
	cattledeer = [6, 4]
	direwolf = [2, 2]
	dragonPeacock = [8, 6]
	evilCentipede = [11, 8]
	featheredSerpent = [16, 8]
	giantAnt = [8, 6]
	giantBat = [0, 4]
	giantBear = [11, 8]
	giantCod = [6, 8]
	giantSalmon = [6, 8]
	hellCaterpillar = [8, 6]
	hellMoth = [12, 9]
	hornedBear = [11, 8]
	hornedRabbit = [7, 5]
	houndDog = [14, 7]
	hoverLizard = [7, 5]
	knightSpider = [8, 6]
	landfish = [7, 5]
	leechLizard = [8, 6]
	megalodon = [30, 15]
	oneEyedOwl = [10, 7]
	orc = [4, 3]
	salamander = [16, 8]
	sissie = [10, 10]
	slime = [3, 2]
	spearToro = [6, 6]
	tempestSerpent = [12, 9]
	wingedCat = [16, 8]
	pegasus = [24, 12]
	unicorn = [24, 12]
	lesserDaemon = [40, 20]
	phantaspore = [10, 7]
	greaterDaemon = [60, 30]
	archDaemon = [80, 40]
